# global settings
title: "GitHub and Government"
description: "GitHub helps government build software better, together"
permalink: "/stories/:title"
url: https://government.github.com
relative_permalinks: false

# build settings
exclude: ["script", "vendor", "bower.json", "Gemfile", "Gemfile.lock", "Rakefile", "readme.md", "package.json", "node_modules"]
markdown: kramdown
plugins:
  - jekyll-avatar
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-sitemap
  - jekyll-octicons

sass:
  style: :compressed
  # Where you keep your scss files
  sass_dir: assets/css/
  # Where sass should look for other scss
  load_paths:
    - node_modules/

# orgs on front page
featured_orgs:
  - gcba
  - nla
  - GeoscienceAustralia
  - qld-gov-au
  - onroerenderfgoed
  - geobolivia
  - dadosgovbr
  - tisorocaba
  - canada-ca
  - wet-boew
  - e-gob
  - City-of-Helsinki
  - ec-europa
  - linz
  - BSI-Bund
  - commonwealth-of-puerto-rico
  - The-Municipality-of-Staffanstorp
  - malmostad
  - ogdch
  - alv-ch
  - city-of-bloomington
  - cityofchattanooga
  - minvws
  - Honolulu
  - mnhrc
  - NYCComptroller
  - ArlingtonCounty
  - sfcta
  - olcf
  - ORNL
  - azgs
  - nysenate
  - State-of-Arizona
  - alphagov
  - BarnsleyCouncil
  - nhsuk
  - cabinetoffice
  - datagovuk
  - dfid
  - east-sussex-county-council
  - hmrc
  - MetOffice
  - 18f
  - CA-CST-SII
  - cfpb
  - cooperhewitt
  - erdc
  - fda
  - gsa
  - hhs
  - nasa
  - USDeptVeteransAffairs
  - virtual-world-framework
  - whitehouse
  - bundestag
  - CodeandoMexico
  - codeforeurope
  - dataviz
  - dobtco
  - KoelnAPI
  - mysociety
  - openva
  - postcode
  - sunlightlabs
  - theodi
  - codeforamerica
  - codeforaustralia
  - okfngr
  - okfn
  - nuknightlab
  - dssg
  - codeforboston
  - teampopong
